### PR TITLE
Created PR templates for template-tool

### PR DESCRIPTION
**Pull request by F-said**
## Changes made
* created two PR templates for bug-fixes and general PR's

## Issues Resolved
* devOps Issue https://github.com/NDCLab/devOps/issues/77

### CODE REVIEW

**Comment by jessb0t** [comment]
@F-said How should we distinguish between a request to merge with dev (which would be reviewed by project lead) versus a request by the project lead to publish a release (aka, merge with main via George's review)?  Given my lack of familiarity with software development, these templates look good for merge with dev, but maybe we want a third one that is specific to merges with main?

**Comment by F-said** [comment]
@jessb0t good point. A PR to main would definitely need to be more extensive and include confirmation that all test cases were passed, documentation was generated, the release is stable (no software-breaking bugs), and maybe more. Will include.

**Comment by F-said** [comment]
@jessb0t Included main PR template

**Comment by jessb0t** [comment]
@F-said Thanks!

**Bug fixes and general:** I committed some tiny punctuation fixes.

**Main:** I find myself wondering if all of this should be required by default, so we might not need to state "if necessary"?  That is, prime the individual to assume that they need to go through all the due diligence before they PR?  Just a thought, but remember that I don't have software dev experience, so please ignore if not valuable!

I will not explicitly review on GH as I feel that @georgebuzzell should do the official review and PR! 😄

**Review by georgebuzzell — APPROVED** [review]
Looks great!!

**Comment by georgebuzzell** [comment]
Looks great, @F-said !

@jessb0t good point about dropping "if necessary". In general, i totally agree that we want to tell the user what to do whenever we can. However, in the cases where "if necessary" is used in these templates, it really is only an "if necessary" thing and does not always apply. so, i think this wording works well here. 

But again, you are totally right @jessb0t that whenever possible, we do not want to "give options" to the user, but "tell them what to do". :)

**Pull request merged**
